/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Crime_management;

/**
 *
 * @author Admin
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        adda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editv = new javax.swing.JButton();
        viewv = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addc = new javax.swing.JButton();
        addv1 = new javax.swing.JButton();
        viewc = new javax.swing.JButton();
        editc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addat = new javax.swing.JButton();
        viewa = new javax.swing.JButton();
        addj = new javax.swing.JButton();
        viewj = new javax.swing.JButton();
        addp = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        deletev = new javax.swing.JButton();
        deletec = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\victim1 (1).jpg")); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\viewculprit.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adda.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("HOMEPAGE");

        editv.setText("EDIT VICTIM RECORD");
        editv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editvActionPerformed(evt);
            }
        });

        viewv.setText("VIEW VICTIM RECORD");
        viewv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewvActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\culpritadd.png")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\criminalrecord.jpg")); // NOI18N

        addc.setText("ADD CULPRIT DETAILS");
        addc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcActionPerformed(evt);
            }
        });

        addv1.setText("ADD VICTIM DETAILS");
        addv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addv1ActionPerformed(evt);
            }
        });

        viewc.setText("VIEW CULPRIT RECORDS");
        viewc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcActionPerformed(evt);
            }
        });

        editc.setText("EDIT CULPRIT RECORD");
        editc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\victim1 (1).jpg")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\victim.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\viewpolice.png")); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\culpritedit.png")); // NOI18N

        addat.setText("ADD ADVOCATE DETAILS");
        addat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addatActionPerformed(evt);
            }
        });

        viewa.setText("VIEW ADVOCATE RECORDS");
        viewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewaActionPerformed(evt);
            }
        });

        addj.setText("ADD JUDGE DETAILS");
        addj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjActionPerformed(evt);
            }
        });

        viewj.setText("VIEW JUDGE RECORDS");
        viewj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewjActionPerformed(evt);
            }
        });

        addp.setText("ADD/SEARCH POLICE");
        addp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\judgeview.png")); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\advocate view.png")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\judge.jpg")); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\viewculprit.png")); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\advocate.jpg")); // NOI18N

        jButton1.setText("VIEW POLICE RECORDS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\police.png")); // NOI18N

        deletev.setText("DELETE VICTIM RECORD");
        deletev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletevActionPerformed(evt);
            }
        });

        deletec.setText("DELETE CULPRIT RECORD");
        deletec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletecActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\delete.jpg")); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Saved Pictures\\delete.jpg")); // NOI18N

        javax.swing.GroupLayout addaLayout = new javax.swing.GroupLayout(adda);
        adda.setLayout(addaLayout);
        addaLayout.setHorizontalGroup(
            addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addaLayout.createSequentialGroup()
                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(addaLayout.createSequentialGroup()
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addaLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jLabel6))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addaLayout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(addp)))
                            .addGroup(addaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel15))
                            .addGroup(addaLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(addv1)))
                            .addGroup(addaLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(viewc)))
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addaLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(viewv)
                                        .addGroup(addaLayout.createSequentialGroup()
                                            .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel14)
                                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(editv)
                                                    .addGroup(addaLayout.createSequentialGroup()
                                                        .addGap(12, 12, 12)
                                                        .addComponent(jLabel4))))
                                            .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(addaLayout.createSequentialGroup()
                                                    .addGap(83, 83, 83)
                                                    .addComponent(jLabel3))
                                                .addGroup(addaLayout.createSequentialGroup()
                                                    .addGap(92, 92, 92)
                                                    .addComponent(jLabel9)))))
                                    .addGroup(addaLayout.createSequentialGroup()
                                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton1)
                                            .addComponent(addat))
                                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(addaLayout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(viewa))
                                            .addGroup(addaLayout.createSequentialGroup()
                                                .addGap(71, 71, 71)
                                                .addComponent(deletev))))))
                            .addGroup(addaLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel7)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel17)))))
                .addGap(71, 71, 71)
                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(69, 69, 69))
                    .addGroup(addaLayout.createSequentialGroup()
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(editc))
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletec)
                            .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addComponent(addj)))))
                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addaLayout.createSequentialGroup()
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addc)
                            .addComponent(jLabel11))
                        .addContainerGap())
                    .addGroup(addaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addaLayout.createSequentialGroup()
                                .addComponent(viewj)
                                .addGap(47, 47, 47))
                            .addGroup(addaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(72, 72, 72))))))
        );
        addaLayout.setVerticalGroup(
            addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addaLayout.createSequentialGroup()
                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(addaLayout.createSequentialGroup()
                                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addv1)
                                            .addComponent(editv))
                                        .addGap(27, 27, 27)
                                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addat)
                                        .addComponent(viewa))
                                    .addComponent(viewc)))
                            .addGroup(addaLayout.createSequentialGroup()
                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addaLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(viewv)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(13, 13, 13))
                                    .addGroup(addaLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addc)
                                            .addComponent(editc))))
                                .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(viewj)
                                    .addComponent(addj))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addp)
                                .addComponent(jButton1)
                                .addComponent(deletev))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addaLayout.createSequentialGroup()
                                .addComponent(deletec)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editvActionPerformed
        // TODO add your handling code here:
        
        Interface i=new Interface();
        EditVictim ev=new EditVictim();
        i.setVisible(false);
        ev.setVisible(true);
        dispose();
    }//GEN-LAST:event_editvActionPerformed

    private void viewvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewvActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        ViewVictim vv=new ViewVictim();
        i.setVisible(false);
        vv.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewvActionPerformed

    private void addcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        AddCulprit ac=new AddCulprit();
        i.setVisible(false);
        ac.setVisible(true);
        dispose();
    }//GEN-LAST:event_addcActionPerformed

    private void addv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addv1ActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        AddVictim av=new AddVictim();
        i.setVisible(false);
        av.setVisible(true);
        dispose();
    }//GEN-LAST:event_addv1ActionPerformed

    private void viewcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        ViewCulprit vc=new ViewCulprit();
        i.setVisible(false);
        vc.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewcActionPerformed

    private void editcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        EditCulprit ec=new EditCulprit();
        i.setVisible(false);
        ec.setVisible(true);
        dispose();
    }//GEN-LAST:event_editcActionPerformed

    private void addatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addatActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        AddAdvocate aa=new AddAdvocate();
        i.setVisible(false);
        aa.setVisible(true);
        dispose();
    }//GEN-LAST:event_addatActionPerformed

    private void addjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        AddJudge aj=new AddJudge();
        i.setVisible(false);
        aj.setVisible(true);
        dispose();
         
    }//GEN-LAST:event_addjActionPerformed

    private void viewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewaActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        ViewAdvocate va=new ViewAdvocate();
        i.setVisible(false);
        va.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewaActionPerformed

    private void viewjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewjActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        ViewJudge vj=new ViewJudge();
        i.setVisible(false);
        vj.setVisible(true);
        dispose();

    }//GEN-LAST:event_viewjActionPerformed

    private void addpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpActionPerformed
        // TODO add your handling code here:
        Interface i=new Interface();
        Police p=new Police();
        i.setVisible(false);
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_addpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ViewPolice vp=new ViewPolice();
        Interface i=new Interface();
        vp.setVisible(true);
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deletevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletevActionPerformed
        // TODO add your handling code here:
        DeleteVictim dv=new DeleteVictim();
        Interface i=new Interface();
        dv.setVisible(true);
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_deletevActionPerformed

    private void deletecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletecActionPerformed
        // TODO add your handling code here:
        DeleteCulprit dc=new DeleteCulprit();
        Interface i=new Interface();
        dc.setVisible(true);
        i.setVisible(false);
        dispose();
    }//GEN-LAST:event_deletecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interface().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adda;
    private javax.swing.JButton addat;
    private javax.swing.JButton addc;
    private javax.swing.JButton addj;
    private javax.swing.JButton addp;
    private javax.swing.JButton addv1;
    private javax.swing.JButton deletec;
    private javax.swing.JButton deletev;
    private javax.swing.JButton editc;
    private javax.swing.JButton editv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton viewa;
    private javax.swing.JButton viewc;
    private javax.swing.JButton viewj;
    private javax.swing.JButton viewv;
    // End of variables declaration//GEN-END:variables
}
